### ISSUE TITLE
Issue-Priorities

### ISSUE THREAD

**Issue by toni254** [upds/quejateya#2]
el boton nueva prioridad redirige a la pantalla de nueva categoria  
![captura de pantalla de 2017-05-01 11-08-35](https://cloud.githubusercontent.com/assets/28201118/25583471/e4701146-2e5f-11e7-9d0b-33407672dc32.png)
 <a class="btn btn-sm btn-success" href="/ismaelc/quejateya/categories/add">

**Comment by enrirq** [comment]
corregido,
