### ISSUE TITLE
Issue-Priorities 

### ISSUE THREAD

**Issue by toni254** [upds/quejateya#4]
los campos de user created y user modified no se deben mostrar en las views asi como tambien el usuario no es el que debe modificar sus valores 
![captura de pantalla de 2017-05-01 12-44-57](https://cloud.githubusercontent.com/assets/28201118/25586261/88dbb4c2-2e6c-11e7-80c3-1dbe463dc565.png)

**Comment by enrirq** [comment]
ya esta resuelto
