### ISSUE TITLE
error  de en boton de view y edit

### ISSUE THREAD

**Issue by eriskjuarez** [upds/quejateya#5]
![captura de pantalla de 2017-05-01 16-08-35](https://cloud.githubusercontent.com/assets/28200515/25592953/c3e8b544-2e88-11e7-8e84-06f40e4bfe2b.png)

**Comment by Kenntjm12** [comment]
Corregido

**Comment by eriskjuarez** [comment]
oks


2017-05-03 21:55 GMT-04:00 Kenntjm12 <notifications@github.com>:
